apiVersion: v1
kind: Service
metadata:
  name: langfactservice
  namespace: {{ .Values.namespace }}
  labels:
    k8s-app: langfactservice
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: ui
      protocol: TCP
  selector:
    k8s-app: langfacts
