apiVersion: v1
kind: Service
metadata:
  name: content-web
  namespace: hack
  labels:
    app: content-web
spec:
  type: ClusterIP  
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  selector:
    app: content-web

---
apiVersion: v1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-web
  namespace: hack
  labels:
    app: content-web
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: content-web
  template:
    metadata:
      labels:
        app: content-web
    spec:
      containers:
      - name: content-web
        image: whatthehackmsft/content-web
        resources:
          requests:
            memory: 128Mi
            cpu: 500m
          limits:
            memory: 256Mi
            cpu: 1
        env:
        - name: CONTENT_API_URL
          value: http://content-api