apiVersion: v1
kind: Service
metadata:
  name: content-api
  namespace: hack
  labels:
    app: content-api
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3001
  selector:
    app: content-api

---
apiVersion: v1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-api
  namespace: hack
  labels:
    app: content-api
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: content-api
  template:
    metadata:
      labels:
        app: content-api
    spec:
      containers:
      - name: content-api
        image: whatthehackmsft/content-api:v2
        resources:
          requests:
            memory: 128Mi
            cpu: 500m
          limits:
            memory: 256Mi
            cpu: 1
        env:
        - name: MONGODB_CONNECTION
          value: mongodb://content-db:27017/contentdb