apiVersion: v1
kind: Service
metadata:
  name: content-db
  namespace: hack
  labels:
    app: content-db
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
  selector:
    app: content-db

---
apiVersion: v1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-db
  namespace: hack
  labels:
    app: content-db
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: content-db
  template:
    metadata:
      labels:
        app: content-db
    spec:
      containers:
      - name: content-db
        image: docker.io/mongo
        resources:
          requests:
            memory: 55M
            cpu: 20m
          limits:
            memory: 256Mi
            cpu: 1
        ports:
        - containerPort:  27017
          name:  mongo-db
        volumeMounts:
        - mountPath: /data/db
          name: azuredisk-db
        - mountPath: /data/configdb
          name: azuredisk-configdb
        imagePullPolicy: Always
      volumes:
        - name: azuredisk-db
          azureDisk:
            kind: Managed
            diskName: mongodb-datadisk
            diskURI: "/subscriptions/49eb4050-650a-40f4-9bc7-0b30ee4c01f9/resourceGroups/mc-playground-lolcat-aks/providers/Microsoft.Compute/disks/mongodb-datadisk"
        - name: azuredisk-configdb
          azureDisk:
            kind: Managed
            diskName: mongodb-configdisk
            diskURI: "/subscriptions/49eb4050-650a-40f4-9bc7-0b30ee4c01f9/resourceGroups/mc-playground-lolcat-aks/providers/Microsoft.Compute/disks/mongodb-configdisk"
      restartPolicy: Always