apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: content-ingress
  namespace: hack
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: 13.93.79.119.nip.io
    http:
      paths:
      - path: /content
        backend:
          serviceName: content-web
          servicePort: 80