apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: langfacts-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: 13.93.79.119.nip.io
    http:
      paths:
      - path: /langfacts
        backend:
          serviceName: langfactservice
          servicePort: 80
        